baseURL = "https://huntbook.predefender.com/"
languageCode = "en-us"
title = "Huntbook by Predefender"
theme = "hugo-theme-relearn"

[taxonomies]

[params]
  editURL = ""
  showVisitedLinks = false
  disableSearch = true
  disableLandingPageButton = true
  disableLanguageSwitchingButton = true
  disableBreadcrumb = true
  disableMermaid = false
  disableNextPrev = true
  ordersectionsby = "weight"
  themeVariant = "predefender"
  titleSeparator = "-"
  huntbookAuthor = "Roger C.B. Johnsen"
  huntbookTitle  = "Huntbook"
  huntbookEdition = "2026.1"

[params.author]
  name = "Roger C.B. Johnsen"
